export enum ECommon {
  EMAIL = "email",
  PASSWORD = "password",
  FIRSTNAME = "firstname",
  LASTNAME = "lastname",
  LOCALE = "locale",
  SIGNUP = "sign up",
  SIGNIN = "sign in",
  SETTING = "setting",
  TABLES = "tables",
  TABLE = "table",
  HOME = "home",
  SIGNOUT = "sign out",
  MINUTES = "minutes",
  SECONDS = "seconds",
  SEARCH = "search",
  MEAL_NAME = "name",
  QUANTITY = "quantity",
  UNIT_PRICE = "unit price",
  TOTAL = "total",
  ORDERED_AT = "ordered at",
  PREVIEW = "preview",
  ORDER = "order",
  SERVED = "served",
  SERVED_AT = "served at",
  SERVING_QUANTITY = "serving quantity",
  SERVED_QUANTITY = "served quantity",
  SERVE = "serve",
  PAY_BILL = "pay bill",
  VAT = "VAT",
  AMOUNT = "amount",
}

export enum EPlaceHolder {
  ENTER_EMAIL = "enter email",
  ENTER_PASSWORD = "enter password",
  ENTER_PHONENUMBER = "enter phone number",
}
