version: '3.8'

services:
  backend_staff:
    restart: always
    container_name: rs_backend_staff
    build:
      context: .
      dockerfile: Dockerfile_staff
    ports:
      - "8020:8000"
    volumes:
      - "./media:/app/media"
    command: python manage_staff.py runserver 0.0.0.0:8000
