FROM python:3.11.1

WORKDIR /app

RUN apt-get update && apt-get install -y gettext
RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
RUN rm -rf staff manage_staff.py
