# Generated by Django 4.1.5 on 2023-01-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
