# Generated by Django 4.1.5 on 2023-02-22 13:59

import base.common.utils.strings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_alter_filemanagement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagement',
            name='thumbnail',
            field=models.ImageField(max_length=500, null=True, upload_to=base.common.utils.strings.get_thumbnail_directory),
        ),
    ]
