# Generated by Django 4.1.5 on 2023-01-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
