# Generated by Django 4.1.5 on 2023-02-25 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='num_ordered',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
