# Generated by Django 4.1.5 on 2023-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
