# Generated by Django 4.1.5 on 2023-01-23 15:34

import base.common.constant.db_fields
import base.common.constant.db_table
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': base.common.constant.db_table.DBTable['MASTER_COUNTRY'],
            },
        ),
        migrations.CreateModel(
            name='MasterFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': base.common.constant.db_table.DBTable['MASTER_FILE_TYPE'],
            },
        ),
        migrations.CreateModel(
            name='MasterMenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': base.common.constant.db_table.DBTable['MASTER_MENU_TYPE'],
            },
        ),
        migrations.CreateModel(
            name='MasterSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': base.common.constant.db_table.DBTable['MASTER_SEX'],
            },
        ),
        migrations.CreateModel(
            name='MasterStaffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': base.common.constant.db_table.DBTable['MASTER_STAFF_TYPE'],
            },
        ),
        migrations.CreateModel(
            name='MasterCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name=base.common.constant.db_table.DBTable['MASTER_CITY'], to='master.mastercountry')),
            ],
            options={
                'db_table': base.common.constant.db_table.DBTable['MASTER_CITY'],
                'unique_together': {(base.common.constant.db_fields.MasterFields['NAME'], base.common.constant.db_fields.MasterCityFields['COUNTRY'])},
            },
        ),
        migrations.CreateModel(
            name='MasterDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name=base.common.constant.db_table.DBTable['MASTER_DISTRICT'], to='master.mastercity')),
            ],
            options={
                'db_table': base.common.constant.db_table.DBTable['MASTER_DISTRICT'],
                'unique_together': {(base.common.constant.db_fields.MasterFields['NAME'], base.common.constant.db_fields.MasterDistrictFields['CITY'])},
            },
        ),
    ]
