# Generated by Django 4.1.5 on 2023-01-25 16:59

import base.common.constant.db_table
import base.common.constant.master
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanagement',
            name='type',
            field=models.ForeignKey(default=base.common.constant.master.MasterFileTypeID['ANY'], on_delete=django.db.models.deletion.RESTRICT, related_name=base.common.constant.db_table.DBTable['FILE_MANAGEMENT'], to='master.masterfiletype'),
        ),
    ]
